### PR TITLE
Submission endpoint POST method - Tayef/submissions api

### PR DESCRIPTION
**Pull request by Tayef-Shah**
WIP: Creating endpoints for submissions

### CODE REVIEW

**Comment by ahmedhamodi** [comment]
What is left to do on this PR? The current changes don't appear to actually define these new submission endpoints.

**Comment by Tayef-Shah** [comment]
You're right, the commits are not related. I opened this draft for people to be aware that the endpoint was being worked on, but at the time I opened this draft, the commits you see above were not merged into master. There's still quite a bit left to do, but I think I should pair with someone to QA the POST operation (since idk how to use our mongo instance)

**Comment by Tayef-Shah** [comment]
Still a WIP, but I added more of the progress for t r a n s p a r e n c y

**Comment by GodGreg** [comment]
@Tayef-Shah We could probably pair on this soonish. @ahmedhamodi and I have agreed that this is the next dev priority along with actually saving the form. 

Feel free to hand this off and enjoy your break; you can rename this PR to reflect the changes done so far and we can merge that.

**Comment by Tayef-Shah** [comment]
In the interest of time, I will merge what I have.

**Review by ahmedhamodi — APPROVED** [review]
Given the new scope of this PR, this looks good to me.

**Review by GodGreg — APPROVED** [review]

**Pull request merged**
